# Generated by Django 5.2.8 on 2025-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField()),
                ('category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database'), ('tools', 'Tools / DevOps'), ('soft', 'Soft Skills'), ('other', 'Other')], default='other', max_length=50)),
                ('years_experience', models.DecimalField(decimal_places=1, help_text='Years of experience (e.g., 1.5, 2.0)', max_digits=4)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class (FontAwesome) or image URL', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description about the skill')),
                ('is_highlight', models.BooleanField(default=False, help_text='Show this skill as highlighted on home page')),
            ],
        ),
    ]
